#version 450

layout(std140, binding = 0) buffer VertexSSBO {
    vec2 vertices[];
} ssbo;

layout (local_size_x = 6, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_LocalInvocationIndex;
    float speed = 0.1;

    if (ssbo.vertices[index].x > 1.0) {
        ssbo.vertices[index].x = -1.0;
    } else {
        ssbo.vertices[index].x = ssbo.vertices[index].x + speed;
    }
}
