#version 450

struct Vertex {
    vec2 position;
};

layout(std140, binding = 0) buffer VertexSSBO {
    Vertex vertices[];
} ssbo;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (ssbo.vertices[index].position.x > 1.0) {
        ssbo.vertices[index].position.x = -1.0;
    } else {
        ssbo.vertices[index].position.x = ssbo.vertices[index].position.x + 0.1;
    }
}
