#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
//
// Shader for testing various GLSL features
//

layout(std140, binding = 0) buffer someBuffer {
    int t;
} buff;

layout (local_size_x = 10, local_size_y = 1, local_size_z = 1) in;

#define thing if (buff.t > 10) return;

void void_return() {
    thing
    buff.t = buff.t + 1;
}

void main() {
    void_return();
    if (buff.t != 0) buff.t = buff.t + 1; else buff.t = buff.t - 1;
    int c = (buff.t != 0) ? 1 : 2;

    switch(buff.t) {
        case 1: buff.t+1;
        case 2: buff.t+2;
        default: buff.t+3;
    }

    uint8_t a = uint8_t(0x00|0x01);

    uint8_t b = uint8_t(10) | uint8_t(12 << 8);
}
